### ISSUE TITLE
Explore section having dropdown menu containing Projects and Blogs

### ISSUE THREAD

**Issue by Gunja22** [CSI-CATT-DMCE/portfolio-hacktoberfest2021#6]
### Refer this
![image](https://user-images.githubusercontent.com/92462111/138546709-1051cd83-b8ee-417f-835b-b554df233e38.png)

**Comment by ayush78781** [comment]
> > @Gunja22 if no one is working over this issue. I would be happy to add this enhancement. Please assign it to me.
> 
> Yes go head

I finished working over it. Kindly review my pull request [here](https://github.com/CSI-CATT-DMCE/portfolio-hacktoberfest2021/pull/21)
